name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.snapcraft_token }}
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run dist
    - name: Publish to Snap Store
      run: snapcraft upload --release edge dist/*.snap
    - uses: actions/upload-artifact@v2
      with:
        name: linux-binaries
        path: dist/digitales-klassenzimmer*
  build-mac:
    name: macOS
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Prepare for mas with provisioning profile
      run: |
        echo '${{ secrets.mac_provisionprofile }}' | base64 -D -o embedded.provisionprofile
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CSC_LINK: ${{ secrets.mac_certs }}
        CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}
      run: |
        npm install
        npm run lint
        npm run dist
    - uses: actions/upload-artifact@v2
      with:
        name: mac-binaries
        path: dist/digitales-klassenzimmer*
  build-windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run dist
    - uses: actions/upload-artifact@v2
      with:
        name: windows-binaries
        path: dist/digitales-klassenzimmer*
